Update spec to final VEX-WG document
openvex/spec pull request #25
Opened 2023-05-30 01:44 UTC by puerco

This PR updates the OpenVEX spec to match the final minimal requirements for VEX as defined by the VEX Working group and [published by CISA](https://www.cisa.gov/sites/default/files/2023-04/minimum-requirements-for-vex-508c.pdf).

The summary of changes to the spec is as follows. Except for the document `version` changing from string to integer, all fields are new so should not break existing consumers.

## Document

* Added wording on the context location to make it clearer it is not versioned until 1.0 (ref https://github.com/openvex/spec/issues/20)
* `version` is now an integer
* Added `last_updated` to record changes to the doc
* `author` is now recommended to be a machine-readable identifier
* `role` is now optional :tada:

## Statement

* `@id` takes an IRI to identify the statement and make it referenceable 
* `version` an integer field, accounts for changes in the statement. Defaults to zero, and may be omitted when so. 
* `last_updated` added to the statement
* supplier an identifier of the supplier of the document

Signed-off-by: Adolfo García Veytia (Puerco) <puerco@chainguard.dev>

2023-05-30 02:10 UTC, puerco commented
Please note that supplier disappeared from the document metadata and is now an optional field at the statement level. Its meaning is different now too, now denoting the supplier of the `product` (previously it specified the supplier of the document).

2023-05-31 16:36 UTC, zmanion commented on OPENVEX-SPEC.md
>  | supplier | ✕ | An optional field specifying who is providing the VEX document. |
Line 163 should be deleted I think, Supplier is (now corrrectly) defined in the Statement section.

2023-06-01 19:53 UTC, puerco commented on OPENVEX-SPEC.md
> +document or other exchange mechanism. |
Good catch, I've removed the newline ant should now work.

2023-06-01 19:54 UTC, puerco commented on OPENVEX-SPEC.md
>  | supplier | ✕ | An optional field specifying who is providing the VEX document. |
I was aiming for only additions in this PR but I've reconsidered from your comment and we should do one change only.

2023-06-01 19:54 UTC, puerco commented on OPENVEX-SPEC.md
>  | supplier | ✕ | An optional field specifying who is providing the VEX document. |
I've pushed another commit removing the supplier.

2023-06-09 12:22 UTC, SecurityCRob approved these changes
For what it is worth, LGTM!  puerco++

2023-06-15 10:55 UTC, tschmidtb51 requested changes
See also #29 and #30

2023-06-15 10:55 UTC, tschmidtb51 commented on OPENVEX-SPEC.md
> +a valid VEX implementation as defined in the [Minimum Requirements for VEX] document published on April 2023 as defined by the VEX Working Group coordinated by the [Cybersecurity & Infrastructure Sec
I suggest to have the clickable links in the doc...
```suggestion
a valid VEX implementation as defined in the [Minimum Requirements for VEX](https://www.cisa.gov/sites/default/files/2023-04/minimum-requirements-for-vex-508c.pdf) document published on April 2023 as defined by the VEX Working Group coordinated by the [Cybersecurity & Infrastructure Security

2023-06-15 10:55 UTC, tschmidtb51 commented on OPENVEX-SPEC.md
> +| author | ✓ | Author is the identifier for the author of the VEX statement. This field should ideally be a machine readable identifier such as an IRI, email address, etc. `author` MUST be an individ
Looks like a word is missing here
```suggestion
| author | ✓ | Author is the identifier for the author of the VEX statement. This field should ideally be a machine readable identifier such as an IRI, email address, etc. `author` MUST be an individual or organization. `author` identity SHOULD be cryptographically associated with the signature of the VEX document or other exchange mechanism. |

2023-06-15 10:55 UTC, tschmidtb51 commented on OPENVEX-SPEC.md
> +| supplier | ✕ | Supplier of the product or subcomponent. |
Please clarify how this fulfills the requirement of https://www.cisa.gov/sites/default/files/2023-04/minimum-requirements-for-vex-508c.pdf:

> [supplier] MUST clearly indicate the [product_id] or [subcomponent_id] to which [supplier]
applies.

If I understand the description correctly, `subcomponents` and `products` might come from different suppliers...

2023-06-19 20:42 UTC, puerco commented on OPENVEX-SPEC.md
> +| supplier | ✕ | Supplier of the product or subcomponent. |
Right, this is an issue we're tackling in an upcoming revision. Right now subcomponents cannot be easily tied back to products (and thus to their suppliers).

2023-07-18 22:33 UTC, puerco commented on OPENVEX-SPEC.md
> +a valid VEX implementation as defined in the [Minimum Requirements for VEX] document published on April 2023 as defined by the VEX Working Group coordinated by the [Cybersecurity & Infrastructure Sec
I think they are there, perhaps I added them in a commit after your review :+1:

2023-07-18 22:35 UTC, puerco commented on OPENVEX-SPEC.md
> +| supplier | ✕ | Supplier of the product or subcomponent. |
This one will be handled in the first revision to the spec coming up in August.

2023-07-18 23:50 UTC, luhring approved these changes

2023-07-18 23:57 UTC, puerco commented
Thanks for your reviews everyone, I'm tagging v0.0.2 of the spec :tada: 

Please note that these changes will not get a technical release. The minor adjustments in v0.0.2 will be rolled into the upcoming updates to the OpenVEX libraries and tools as part of the v0.1.0 revision.

2023-07-18 23:57 UTC, merged

2023-07-19 12:09 UTC, SecurityCRob commented
Congratulations team!  To 0.0.2 and BEYOND!!!

Cheers,

CRob
Director of Security Communications
Intel Product Assurance and Security


From: Puerco ***@***.***>
Sent: Tuesday, July 18, 2023 7:57 PM
To: openvex/spec ***@***.***>
Cc: Robinson, Christopher ***@***.***>; Comment ***@***.***>
Subject: Re: [openvex/spec] Update spec to final VEX-WG document (PR #25)


Thanks for your reviews everyone, I'm tagging v0.0.2 of the spec 🎉

Please note that these changes will not get a technical release. The minor adjustments in v0.0.2 will be rolled into the upcoming updates to the OpenVEX libraries and tools as part of the v0.1.0 revision.

—
Reply to this email directly, view it on GitHub<https://github.com/openvex/spec/pull/25#issuecomment-1641140485>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQRFDLEO7A56OWN5L6SOFULXQ4PGPANCNFSM6AAAAAAYTKRALM>.
You are receiving this because you commented.Message ID: ***@***.******@***.***>>